import { ProjectDetails } from "./types/ProjectDetails";

export const projectDetails: ProjectDetails[] = [
    {
        id: 1,
        slug: "liora",
        title: "Liora",
        productCard:"/assets/productcardliora.jpg",
        course: "School project 2025 - Frontend development",
        description: ["Liora is a poster webshop, designed with a modern and clean design, focused on providing a user-friendly experience. Key features include a home page, product detail page, shopping cart, and a checkout page. Users can add, remove, and adjust quantities of posters in the shopping cart. It automatically calculates the total price based on selected products.",
        "This project was developed using Agile methodology, with daily standups, sprint planning, and retrospectives for continuous improvement."],
        tech: ["HTML", "TypeScript", "SCSS"],
        github: "https://github.com/malinjansson/LioraWebshop",
        topimage: "/assets/liora/topimage.jpg",
        demo: ["/assets/liora/demo_one.jpg", 
        "/assets/liora/demo_two.jpg",
        "/assets/liora/demo_three.jpg",
        "/assets/liora/demo_four.jpg",
        "/assets/liora/demo_five.jpg",
        "/assets/liora/demo_six.jpg",
        "/assets/liora/demo_seven.jpg",
        ]
    },
    {
        id: 2,
        slug: "auctionhouse",
        title: "Auction House",
        productCard: "/assets/productcardauctionhouse.jpg",
        course: "School project 2025 - System development",
        description: ["This project is a real-time auction site. Users can place bids and see live updates in the browser. The frontend includes an overview of all auctions and a detailed auction page with bid history and a bid form. The server validates bids and handles real-time updates. The project also supports room-based WebSocket communication to separate individual auctions."],
        tech: ["Node.js", "Express.js", "WebSockets","TypeScript", "SCSS"],
        github: "https://github.com/malinjansson/Auctionhouse",
        topimage: "/assets/auctionhouse/topimage.jpg",
        demo: ["/assets/auctionhouse/demo_one.jpg", 
               "/assets/auctionhouse/demo_two.jpg",
               "/assets/auctionhouse/demo_three.jpg"
            ]
    },
    {
        id: 3,
        slug: "moviecloud",
        title: "MovieCloud",
        productCard:"/assets/productcardmoviecloud.jpg",
        course: "System development framework, 2025",
        description: ["MovieCloud is a movie site built using React, fetching and displaying movie information from an external API. Users can search for movies and view movie details.",
        "I gained hands-on experience in API integration, extended my skills in React, and deepened my understanding of useState and the useEffect hook."],
        tech: ["API", "React", "TypeScript", "SCSS"],
        github: "https://github.com/malinjansson/MovieCloud", 
        livedemo: "https://apimoviecloud.vercel.app/",
        topimage:  "/assets/moviecloud/topimage.jpg",
        demo: ["/assets/moviecloud/demo_one.png", 
        "/assets/moviecloud/demo_two.png",
        "/assets/moviecloud/demo_three.jpg",
        ]
    },
    {
        id: 4,
        slug: "posterstories",
        title: "Poster Stories",
        productCard:"/assets/productcardposterstories.jpg",
        course: "School project 2025 - System development",
        description: ["Poster stories is a e-commerce website built using PHP and MySQL. The application features a normalized database and includes user and product management. Key features include:", 
        "• Homepage displaying 10 bestsellers",
        "• All products belong to one category",
        "• Global search functionality",
        "• Search and category listing, sortable by name and price (asc & desc)",
        "• PDP (Product Detail Pages)",
        "• Customer/user registration and login feature",
        "• Users can add products to the shopping cart and it is stored in the database",
        "• Admin page (edit and delete products)"],
        tech: ["PHP", "MySQL", "Bootstrap"],
        github: "https://github.com/malinjansson/Posterstories",
        topimage: "/assets/posterstories/topimage.jpg",
        demo: ["/assets/posterstories/demo_one.jpg", 
        "/assets/posterstories/demo_two.jpg",
        "/assets/posterstories/demo_three.jpg",
        "/assets/posterstories/demo_four.jpg",
        "/assets/posterstories/demo_five.jpg",
        "/assets/posterstories/demo_six.jpg",
        "/assets/posterstories/demo_seven.jpg",
        ]
    },
    {
        id: 5,
        slug: "todolist",
        title: "Todo list",
        productCard:"/assets/productcardtodo.jpg",
        course: "System development framework, 2025",
        description: ["A todo-list application built with Vite and React. The user can add todos, remove todos, mark as done/undone and sort todos."],
        tech: ["React", "TypeScript", "SCSS"],
        github: "https://github.com/malinjansson/TodoReact",
        livedemo: "https://malintodos.vercel.app/",
        topimage: "/assets/todos/topimage.jpg",
        demo: ["/assets/todos/demo_one.png", 
        "/assets/todos/demo_two.jpg",
        "/assets/todos/demo_three.png"
        ]
    },
]